apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: byl0po0f4-nodejs 
  janus-idp.io/tekton: byl0po0f4-nodejs
  backstage.io/kubernetes-id: byl0po0f4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: byl0po0f4-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml