apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: byl0po0f4-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: byl0po0f4-nodejs 
  name: byl0po0f4-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: byl0po0f4-nodejs
    weight: 100 
